/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#383a38",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#e2e3e0",
        "on-primary-container": "#77ac90",
        "primary": "#9cd2b5",
        "on-secondary-fixed-variant": "#474646",
        "surface": "#121413",
        "error": "#ffb4ab",
        "tertiary": "#e9c349",
        "on-surface": "#e2e3e0",
        "secondary": "#c8c6c5",
        "primary-fixed-dim": "#9cd2b5",
        "surface-container-low": "#1a1c1b",
        "surface-container-high": "#282a29",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-on-surface": "#2f3130",
        "background": "#121413",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0d0f0e",
        "on-tertiary-fixed-variant": "#574500",
        "tertiary-container": "#cba72f",
        "tertiary-fixed": "#ffe088",
        "surface-container-highest": "#333534",
        "on-error": "#690005",
        "on-background": "#e2e3e0",
        "on-primary-fixed-variant": "#1b503a",
        "outline-variant": "#404943",
        "surface-variant": "#333534",
        "on-secondary-container": "#bab8b7",
        "on-secondary": "#313030",
        "inverse-primary": "#356850",
        "primary-fixed": "#b8efd0",
        "surface-dim": "#121413",
        "primary-container": "#06402b",
        "surface-tint": "#9cd2b5",
        "on-tertiary-fixed": "#241a00",
        "outline": "#8a938c",
        "on-surface-variant": "#c0c9c1",
        "surface-container": "#1e201f",
        "on-tertiary": "#3c2f00",
        "secondary-container": "#4a4949",
        "tertiary-fixed-dim": "#e9c349",
        "on-tertiary-container": "#4e3d00",
        "on-primary-fixed": "#002114",
        "on-primary": "#003825",
        "secondary-fixed": "#e5e2e1"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "logo": ["Cinzel", "serif"]
      }
    },
  },
  plugins: [],
}
